### ISSUE TITLE
Blasting Core locks the server

### ISSUE THREAD

**Issue by SuperKael** [DaedalusGame/EmbersRekindled#157]
Using the blasting core on a tightly-packed group of mobs occasionally causes the server to get stuck in a loop, ultimately resulting in the server watchdog shutting it down.
The loop looks something like this:

```
at teamroots.embers.itemmod.ModifierBlastingCore.onHit(ModifierBlastingCore.java:71) ~[ModifierBlastingCore.class:?]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1419_ModifierBlastingCore_onHit_LivingHurtEvent.invoke(.dynamic) ~[?:?]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:603) ~[ForgeHooks.class:?]
at net.minecraft.entity.EntityLivingBase.func_70665_d(EntityLivingBase.java:1410) ~[vp.class:?]
at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:926) ~[vp.class:?]
at net.minecraft.entity.monster.EntityMob.func_70097_a(EntityMob.java:70) ~[ade.class:?]
at net.minecraft.entity.monster.EntityZombie.func_70097_a(EntityZombie.java:233) ~[adt.class:?]
at teamroots.embers.itemmod.ModifierBlastingCore.onHit(ModifierBlastingCore.java:71) ~[ModifierBlastingCore.class:?]
```

I'm guessing that the explosion is propagating back and forth between the mobs? I don't really know, I'm not the authority here. Anyways, while I'm at it, another problem with the blasting core: if used on mobs that are abnormally close to a block, (in my case, a Random Things spirit that was directly above a block - since it's so small, it extremely close to the block) the explosion from the Blasting Core can break the block(s). Since the explosions caused by hitting mobs don't normally damage blocks, this seems unintended.

**Comment by machinespray** [comment]
I also experienced this bug. It definitly seems to break blocks when it shouldn't. Dirt broke but stone didn't. It's a pretty severe issue. I tried to append a screenshot of the particles and effects, but my computer was pretty frozen up and I didn't get one.

**Comment by Jack-0-Spades** [comment]
I have also experienced this bug with the blasting core locking the server.

> 
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
        at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:604) ~[ForgeHooks.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70665_d(EntityLivingBase.java:1410) ~[vp.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:926) ~[vp.class:?]
        at net.minecraft.entity.passive.EntityAnimal.func_70097_a(SourceFile:66) ~[zv.class:?]
        at teamroots.embers.itemmod.ModifierBlastingCore.onHit(ModifierBlastingCore.java:71) ~[ModifierBlastingCore.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_143_ModifierBlastingCore_onHit_LivingHurtEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
        at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:604) ~[ForgeHooks.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70665_d(EntityLivingBase.java:1410) ~[vp.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:926) ~[vp.class:?]
        at net.minecraft.entity.passive.EntityAnimal.func_70097_a(SourceFile:66) ~[zv.class:?]
        at teamroots.embers.itemmod.ModifierBlastingCore.onHit(ModifierBlastingCore.java:71) ~[ModifierBlastingCore.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_143_ModifierBlastingCore_onHit_LivingHurtEvent.invoke(.dynamic) ~[?:?]

**Comment by ghost** [comment]
Same issue here, client is fine, but the SSP server crashed. Crashing when I hit more than one mob with a Blasting core weapon(it doesn't need to be a large group, any situation where a second mob gets hit by the explosion causes the crash). Here is the crash log:

https://paste.dimdev.org/aqukavopot.mccrash

Here is the pick in question(Sweeping Edge, Sharpness, Magnetic, Efficiency, Blasting 1). I also tested without Sweeping edge/Magnetic, the issue persists:

https://i.imgur.com/W9lvpsF.png

**Comment by DaedalusGame** [comment]
Should be fixed now, let me know if it's not
