### ISSUE TITLE
Crasher with Evilcraft blood in a reservoir

### ISSUE THREAD

**Issue by gchpaco** [DaedalusGame/EmbersRekindled#158]
Ran into this earlier.  Evilcraft blood in a reservoir.

[crash-2019-04-22_19.49.00-client.txt](https://github.com/DaedalusGame/EmbersRekindled/files/3105345/crash-2019-04-22_19.49.00-client.txt)

**Comment by gchpaco** [comment]
I should note.  Reservoir had a mechanical core, a valve ring, and then another ring on top, but didn't crash until I added the fluid.

**Comment by gchpaco** [comment]
I am wearing ashen goggles there and am looking at either the ring on top or the valve ring, so that's probably part of the issue, after studying some of the code.

**Comment by DaedalusGame** [comment]
huh i wonder if the mystmech capability is null

**Comment by DaedalusGame** [comment]
oof 
https://github.com/DaedalusGame/EmbersRekindled/blob/ac63aa44e35101353accde9eb504a2b0aa2e93e4/src/main/java/teamroots/embers/tileentity/TileEntityStoneValve.java#L113

**Comment by RauzKindred** [comment]
Ah, didn't see this, having the same issue but using different set of mods, the caminite valve seems to be the cause, I tested doing a fully built reservoir with all attachments except for the valve, and no issues, no lag. I even pumped in and out various liquids to ensure nothing else was causing it. The second i added the valve though it bugged out my single player file and made it unplayable. Don't know if its an argument with the other mods or if its just the valve.

**Comment by Sirios16** [comment]
Has the bug returned or has it ever gone away?

**Comment by tyon2006** [comment]
hey i'm actually still getting this exact issue. on current version. As soon as I mouse over with ashen goggles on, *poof* crashes

**Comment by DaedalusGame** [comment]
wtf

**Comment by tyon2006** [comment]
[22:30:46] [Client thread/FATAL]: Unreported exception thrown!
java.lang.NullPointerException: null
	at teamroots.embers.compat.MysticalMechanicsIntegration.addCapabilityMechanicalDescription(MysticalMechanicsIntegration.java:226) ~[MysticalMechanicsIntegration.class:?]
	at teamroots.embers.compat.MysticalMechanicsIntegration.addCapabilityInformation(MysticalMechanicsIntegration.java:219) ~[MysticalMechanicsIntegration.class:?]
	at teamroots.embers.EventManager.addCapabilityInformation(EventManager.java:438) ~[EventManager.class:?]
	at teamroots.embers.EventManager.onGameOverlayRender(EventManager.java:419) ~[EventManager.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1315_EventManager_onGameOverlayRender_Post.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at net.minecraftforge.client.GuiIngameForge.post(GuiIngameForge.java:911) ~[GuiIngameForge.class:?]
	at net.minecraftforge.client.GuiIngameForge.renderHUDText(GuiIngameForge.java:741) ~[GuiIngameForge.class:?]
	at net.minecraftforge.client.GuiIngameForge.renderGameOverlay(GuiIngameForge.java:173) ~[GuiIngameForge.class:?]
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1098) ~[buq.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119) ~[bib.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:3942) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[22:30:46] [Client thread/FATAL]: Minecraft ran into a problem! Report saved to: C:\Users\Domo\Twitch\Minecraft\Instances\MMO - Let's Go (1)\crash-reports\crash-2020-07-21_22.30.46-client.txt
---- Minecraft Crash Report ----
// But it works on my machine.

Time: 2020-07-21 22:30:46 EDT
Description: Unexpected error

java.lang.NullPointerException
    at teamroots.embers.compat.MysticalMechanicsIntegration.addCapabilityMechanicalDescription(MysticalMechanicsIntegration.java:226)
    at teamroots.embers.compat.MysticalMechanicsIntegration.addCapabilityInformation(MysticalMechanicsIntegration.java:219)
    at teamroots.embers.EventManager.addCapabilityInformation(EventManager.java:438)
    at teamroots.embers.EventManager.onGameOverlayRender(EventManager.java:419)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1315_EventManager_onGameOverlayRender_Post.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.client.GuiIngameForge.post(GuiIngameForge.java:911)
    at net.minecraftforge.client.GuiIngameForge.renderHUDText(GuiIngameForge.java:741)
    at net.minecraftforge.client.GuiIngameForge.renderGameOverlay(GuiIngameForge.java:173)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1098)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by TheXTrunner** [comment]
this happened to me with the tinker's lens and a reservoir https://paste.ee/p/vRTKG

**Comment by DaedalusGame** [comment]
Update embers rekindled

**Comment by TheXTrunner** [comment]
updated, got an error again
https://paste.ee/p/LHcQP

**Comment by DaedalusGame** [comment]
Update mystical mechanics
