### ISSUE TITLE
NPE on TileEntityFurnaceTop

### ISSUE THREAD

**Issue by klugemonkey** [DaedalusGame/EmbersRekindled#196]
Null Pointer Exception in EmbersRekindled-1.13-hotfix2.jar.
Running on 1.12.2 with the Project Ozone 3 Modpack (Titan Mode) 3.1.44.

java.lang.NullPointerException: Null string not allowed
	at java.util.Objects.requireNonNull(Objects.java:228)
	at net.minecraft.nbt.NBTTagString.<init>(NBTTagString.java:19)
	at net.minecraft.nbt.NBTTagCompound.func_74778_a(NBTTagCompound.java:138)
	at net.minecraftforge.fluids.FluidStack.writeToNBT(FluidStack.java:107)
	at net.minecraftforge.fluids.FluidTank.writeToNBT(FluidTank.java:77)
	at net.minecraftforge.fluids.capability.TileFluidHandler.func_189515_b(TileFluidHandler.java:47)
	at teamroots.embers.tileentity.TileEntityOpenTank.func_189515_b(TileEntityOpenTank.java:19)
	at teamroots.embers.tileentity.TileEntityFurnaceTop.func_189515_b(TileEntityFurnaceTop.java:73)
	at teamroots.embers.tileentity.TileEntityFurnaceTop.func_189517_E_(TileEntityFurnaceTop.java:88)
	at teamroots.embers.tileentity.TileEntityFurnaceTop.func_189518_D_(TileEntityFurnaceTop.java:94)
	at teamroots.embers.util.Misc.syncTE(Misc.java:266)
	at teamroots.embers.tileentity.TileEntityFurnaceTop.func_70296_d(TileEntityFurnaceTop.java:131)
	at teamroots.embers.tileentity.TileEntityFurnaceTop$2.onContentsChanged(TileEntityFurnaceTop.java:54)
	at net.minecraftforge.fluids.FluidTank.fillInternal(FluidTank.java:182)
	at net.minecraftforge.fluids.FluidTank.fill(FluidTank.java:149)
	at teamroots.embers.tileentity.TileEntityFurnaceTop$2.fill(TileEntityFurnaceTop.java:63)
	at teamroots.embers.tileentity.TileEntityFurnaceBottom.func_73660_a(TileEntityFurnaceBottom.java:162)
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

**Comment by DaedalusGame** [comment]
what did you do to have this happen?
