### ISSUE TITLE
Extremely Long Startup Times with JEI

### ISSUE THREAD

**Issue by TheTennessee** [DaedalusGame/EmbersRekindled#291]
So for several versions now I have been having such extremely long loading times I cannot use the mod and retain my sanity. Let me explain, I was running version 13 hotfix 2, and I keep going back to it out of necessity. I have tested every version until version 18 now, and they all do the same thing.

Loading the game in the technic launcher, having added this mod to the 1.12.2 pack, I get to the same section "Loading - Finishing Up 6/7" "Load Complete - Just Enough Items" and there it hangs for the next 30 minutes. I have the console open, and the entire time I get this error:

`[B#617]  [11:06:04] [Client thread/ERROR]: Found a broken recipe: teamroots.embers.recipe.AnvilRepairFakeRecipe@7fd7afef
[B#617]  Failed to get ingredients from recipe wrapper
[B#617]  
[B#617]  java.lang.ClassCastException: null`

I get about a thousand or so of these of the course of the next 30 minutes. Eventually, the mod does load, I get to play, but I can't deal with this load time. I have much less load time when I use the aforementioned version 13 hotfix 2, but I do obviously have other problems. I just can't keep waiting for my game to load for this long, so I suffer through. Please lord fix this in the next version.

**Comment by DaedalusGame** [comment]
i can't fix this, this is caused by something (other than embers) throwing an exception in attach capability

**Comment by TheTennessee** [comment]
What do you mean you can't fix this? It's in one version of your mod but not another? So logically speaking, it is something you put into the mod that is at least triggering it, if not the root cause. Can't you add a config option to turn off the trigger for better compatibility? Anything?

**Comment by DaedalusGame** [comment]
actually i additionally can't fix this because you didn't post a log, `java.lang.ClassCastException: null` tells me nothing, I need a full stacktrace.

**Comment by dasrukh** [comment]
Same issue here, not sure what recipe it is but it seems like it has to do with the dawnstone anvil. I'm going to disable mods to try and figure out which one it is. If I come across it, I will let you know, but it does add over an hour to the load time of the game, and I have a somewhat gamy laptop. Here is a bit of the output log:

<details><summary>Output Log</summary>
<p>

07:35:09.328
game
at teamroots.embers.recipe.AnvilBreakdownRecipe.lambda$new$0(AnvilBreakdownRecipe.java:17) ~[AnvilBreakdownRecipe.class:?]
07:35:09.328
game
at teamroots.embers.recipe.AnvilBreakdownRecipe$$Lambda$8117/1502268896.test(Unknown Source) ~[?:?]
07:35:09.328
game
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[?:1.8.0_51]
07:35:09.328
game
at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_51]
07:35:09.328
game
at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_51]
07:35:09.328
game
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51]
07:35:09.328
game
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51]
07:35:09.328
game
at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_51]
07:35:09.328
game
at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_51]
07:35:09.328
game
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51]
07:35:09.328
game
at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_51]
07:35:09.328
game
at teamroots.embers.util.IngredientSpecial.cacheMatchingStacks(IngredientSpecial.java:58) ~[IngredientSpecial.class:?]
07:35:09.328
game
at teamroots.embers.util.IngredientSpecial.func_193365_a(IngredientSpecial.java:43) ~[IngredientSpecial.class:?]
07:35:09.328
game
at teamroots.embers.recipe.DawnstoneAnvilRecipe.getTopInputs(DawnstoneAnvilRecipe.java:31) ~[DawnstoneAnvilRecipe.class:?]
07:35:09.328
game
at teamroots.embers.compat.jei.wrapper.DawnstoneAnvilWrapper.getIngredients(DawnstoneAnvilWrapper.java:19) ~[DawnstoneAnvilWrapper.class:?]
07:35:09.328
game
at mezz.jei.recipes.RecipeRegistry.getIngredients(RecipeRegistry.java:290) ~[RecipeRegistry.class:?]
07:35:09.328
game
at mezz.jei.recipes.RecipeRegistry.addRecipeUnchecked(RecipeRegistry.java:274) ~[RecipeRegistry.class:?]
07:35:09.328
game
at mezz.jei.recipes.RecipeRegistry.addRecipe(RecipeRegistry.java:262) [RecipeRegistry.class:?]
07:35:09.328
game
at mezz.jei.recipes.RecipeRegistry.addRecipe(RecipeRegistry.java:234) [RecipeRegistry.class:?]
07:35:09.328
game
at mezz.jei.recipes.RecipeRegistry.addRecipes(RecipeRegistry.java:171) [RecipeRegistry.class:?]
07:35:09.328
game
at mezz.jei.recipes.RecipeRegistry.<init>(RecipeRegistry.java:98) [RecipeRegistry.class:?]
07:35:09.328
game
at mezz.jei.startup.ModRegistry.createRecipeRegistry(ModRegistry.java:335) [ModRegistry.class:?]
07:35:09.328
game
at mezz.jei.startup.JeiStarter.start(JeiStarter.java:81) [JeiStarter.class:?]
07:35:09.328
game
at mezz.jei.startup.ProxyCommonClient.loadComplete(ProxyCommonClient.java:136) [ProxyCommonClient.class:?]
07:35:09.328
game
at mezz.jei.JustEnoughItems.loadComplete(JustEnoughItems.java:55) [JustEnoughItems.class:?]
07:35:09.328
game
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
07:35:09.328
game
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
07:35:09.328
game
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
07:35:09.328
game
at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
07:35:09.328
game
at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637) [FMLModContainer.class:?]

</p>
</details> `07:35:09.328

**Comment by dasrukh** [comment]
> 

In my instance, it was conflicting with exnihiloomnia_1.12.2-0.0.2.jar, it seems like it doesn't like something about the hammer and the dawnstone anvil, something to do with fake recipes. Just disabled the mod since it hasn't been updated since 2019 and i'm not playing isle survival this playthrough.
