### ISSUE TITLE
Server Crash with NPE on EmbersRekindled-1.18

### ISSUE THREAD

**Issue by natebc** [DaedalusGame/EmbersRekindled#301]
```
Time: 2022-01-11 19:58:30 UTC
Description: Ticking block entity

java.lang.NullPointerException: Null string not allowed
    at java.util.Objects.requireNonNull(Objects.java:228)
    at net.minecraft.nbt.NBTTagString.<init>(NBTTagString.java:19)
    at net.minecraft.nbt.NBTTagCompound.setString(NBTTagCompound.java:138)
    at net.minecraftforge.fluids.FluidStack.writeToNBT(FluidStack.java:107)
    at net.minecraftforge.fluids.FluidTank.writeToNBT(FluidTank.java:77)
    at net.minecraftforge.fluids.capability.TileFluidHandler.writeToNBT(TileFluidHandler.java:47)
    at teamroots.embers.tileentity.TileEntityOpenTank.writeToNBT(TileEntityOpenTank.java:19)
    at teamroots.embers.tileentity.TileEntityFurnaceTop.writeToNBT(TileEntityFurnaceTop.java:73)
    at teamroots.embers.tileentity.TileEntityFurnaceTop.getUpdateTag(TileEntityFurnaceTop.java:88)
    at teamroots.embers.tileentity.TileEntityFurnaceTop.getUpdatePacket(TileEntityFurnaceTop.java:94)
    at teamroots.embers.util.Misc.syncTE(Misc.java:290)
    at teamroots.embers.tileentity.TileEntityFurnaceTop.markDirty(TileEntityFurnaceTop.java:132)
    at teamroots.embers.tileentity.TileEntityFurnaceTop$2.onContentsChanged(TileEntityFurnaceTop.java:54)
    at net.minecraftforge.fluids.FluidTank.fillInternal(FluidTank.java:182)
    at net.minecraftforge.fluids.FluidTank.fill(FluidTank.java:149)
    at teamroots.embers.tileentity.TileEntityFurnaceTop$2.fill(TileEntityFurnaceTop.java:63)
    at teamroots.embers.tileentity.TileEntityFurnaceBottom.TickCentral_TrueITickableUpdate(TileEntityFurnaceBottom.java:163)
    at com.github.terminatornl.tickcentral.api.TickHub.trueUpdate(TickHub.java:48)
    at com.github.terminatornl.laggoggles.Main.redirectUpdate(Main.java:91)
    at teamroots.embers.tileentity.TileEntityFurnaceBottom.update(TileEntityFurnaceBottom.java)
    at com.zeitheron.hammercore.asm.McHooks.tickTile(McHooks.java:38)
    at net.minecraft.world.World.updateEntities(World.java:1838)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)
```

Gist with end of server's latest.log and the crashreport: https://gist.github.com/natebc/a45dfddcdd9f3e2c8f9a935dd62c58a2

Was linking an Ember Activator + Emitter to a Melter + Receptor. It's been a minute since I Embered and was having trouble getting the melter to work (it had 4 iron ingots in it) and was trying to find where to put the receptor. When i put it on the bottom part of the melter and linked it to the Emitter the server went kablooey.

I'll also report this to the modpack and link that issue here.

Please let me know if any further info is needed.

**Comment by natebc** [comment]
The world survived the crash, other than voiding the contents of the melter and seems to be working good now so this might be pointless to run down unless you're just curious.
