### ISSUE TITLE
Mechanical Pump Causes Crash

### ISSUE THREAD

**Issue by Protnore** [DaedalusGame/EmbersRekindled#307]
Upon using the mechanical pump, it turns on and begins to slowly animate - but causes a crash the instant that the pump animation finishes (as it sucks up water). Interestingly enough, this wasn't originally something that was happening, but after I added more mods to my personal world it began to happen and I have since had to remove all of the mechanical pumps to avoid future issues.

I have reviewed the code with my limited knowledge and cannot see reference to what mod is causing the clash with Embers Rekindled, I can see Abyssalcraft is mentioned - but I had that installed when the mechanical pumps were working as well. See attached crash log for reference. If you can even identify which mod is causing this issue I would be more than willing to remove it, but I can't figure out what's going on at all.

[crash-2022-07-28_23.55.01-server.txt](https://github.com/DaedalusGame/EmbersRekindled/files/9210383/crash-2022-07-28_23.55.01-server.txt)

**Comment by celulamp** [comment]
Same issue when I was trying to use the pump on lava.

[15:23:38] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:773) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_382]
Caused by: java.lang.ClassCastException: net.minecraft.block.BlockStaticLiquid cannot be cast to net.minecraftforge.fluids.BlockFluidBase
        at teamroots.embers.util.FluidUtil.getFluid(FluidUtil.java:13) ~[FluidUtil.class:?]
        at teamroots.embers.tileentity.TileEntityPumpBottom.attemptPump(TileEntityPumpBottom.java:124) ~[TileEntityPumpBottom.class:?]
        at teamroots.embers.tileentity.TileEntityPumpBottom.TickCentral_TrueITickableUpdate(TileEntityPumpBottom.java:182) ~[TileEntityPumpBottom.class:?]
        at com.github.terminatornl.tickcentral.api.TickHub.trueUpdate(TickHub.java:48) ~[TickHub.class:3.2]
        at com.github.terminatornl.laggoggles.Main.redirectUpdate(Main.java:94) ~[LagGoggles-1.12.2-5.9-140.jar:1.12.2-5.9-140]
        at teamroots.embers.tileentity.TileEntityPumpBottom.func_73660_a(TileEntityPumpBottom.java) ~[TileEntityPumpBottom.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1838) ~[amu.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) ~[oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) ~[MinecraftServer.class:?]
        ... 4 more
[15:23:38] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: C:\Users\Noah\curseforge\minecraft\Instances\1.12.2\.\crash-reports\crash-2023-10-08_15.23.38-server.txt
